import { useEffect, useState } from "react";

import type { NextPage } from "next";
import Head from "next/head";
import Router, { useRouter } from "next/router";
import toast, { Toaster } from "react-hot-toast";
import Image from "next/image";
import { handleSignupState } from "../redux/actions/auth";
import { useAppDispatch, useAppSelector } from "../redux/hooks";
import styles from "../styles/Merchant/signup.module.scss";

const SignUp: NextPage = () => {
  const router = useRouter();
  const dispatch = useAppDispatch();

  const [email, setEmail] = useState<string>("");
  const [password, setPassword] = useState<string>("");
  const [role, setRole] = useState<string>("Admin");

  const { error, user, isAuthenticated } = useAppSelector(
    (state) => state.user
  );
  console.log(user);
  console.log(isAuthenticated);

  const handleLogin = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    setRole("Admin");
    dispatch(
      handleSignupState({
        email,
        password,
        role,
      })
    );
  };

  // );
  console.log(role);

  useEffect(() => {
    if (error) {
      toast.error((error as any).message);
    }

    if (isAuthenticated) {
      toast.success("created Successfully");
      Router.push("/onboarding/profile");
    }
  }, [error, isAuthenticated, user]);

  const [showPassword, setshowPassword] = useState(false);

  const showPasswordHandler = useCallback(() => {
    setshowPassword(!showPassword);
  }, [showPassword]);
  return (
    <div className="">
      <Toaster position="bottom-center" />

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className={styles.SectionBox}>
        <div className={styles.imgBx}>
          <img
            src="/omratrade/el.png"
            className={styles.img_signup}
            alt="girl"
          />
        </div>

        <div className={styles.contentBx}>
          <div className={styles.formBx}>
            <h2>Sign up</h2>
            <form onSubmit={handleLogin}>
              <div>
                <span>Email id</span>
                <input
                  className={styles.InputBox}
                  type="email"
                  id="email"
                  onChange={(e) => setEmail(e.target.value)}
                />
              </div>

              <div>
                <span>Password</span>
                <div className={styles.passwordbox}>
                  <input
                    className={styles.InputBox}
                    type={showPassword ? "text" : "password"}
                    name=""
                    onChange={(e) => setPassword(e.target.value)}
                  />
                  <div
                    className={` ${styles.passwordshowicon} ${styles.passwordshow} `}
                  ></div>
                  <div
                    onClick={showPasswordHandler}
                    className={` ${styles.passwordhideicon} ${styles.passwordshow} `}
                  >
                    {showPassword ? (
                      <Image
                        src="/svg/eye-slash-solid.svg"
                        width={20}
                        height={20}
                        className={styles.passwordhideiconn}
                      ></Image>
                    ) : (
                      <Image
                        src="/svg/eye-solid.svg"
                        width={20}
                        height={20}
                        className={styles.passwordshowiconn}
                      ></Image>
                    )}
                  </div>
                </div>
              </div>
              <div>
                <span>Confirm Password</span>
                <div className={styles.passwordbox}>
                  <input
                    className={styles.InputBox}
                    type={showPassword ? "text" : "password"}
                    name=""
                    onChange={(e) => setPassword(e.target.value)}
                  />
                  <div
                    className={` ${styles.passwordshowicon} ${styles.passwordshow} `}
                  ></div>
                  <div
                    onClick={showPasswordHandler}
                    className={` ${styles.passwordhideicon} ${styles.passwordshow} `}
                  >
                    {showPassword ? (
                      <Image
                        src="/svg/eye-slash-solid.svg"
                        width={20}
                        height={20}
                        className={styles.passwordhideiconn}
                      ></Image>
                    ) : (
                      <Image
                        src="/svg/eye-solid.svg"
                        width={20}
                        height={20}
                        className={styles.passwordshowiconn}
                      ></Image>
                    )}
                  </div>
                </div>
              </div>
              <input
                type="submit"
                value="Sign up"
                name=""
                className={styles.buttonsection}
                onClick={() => {
                  alert("Login");
                }}
              />
            </form>
          </div>
        </div>
      </section>
    </div>
  );
};

export default SignUp;
