export const LOGIN_STATE_REQUEST = 'LOGIN_STATE_REQUEST';
export const LOGIN_STATE_SUCCESS = 'LOGIN_STATE_SUCCESS';
export const LOGIN_STATE_FAILURE = 'SET_LOGIN_FAILURE';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const SET_SIGNUP_REQUEST = 'SET_SIGNUP_REQUEST';
export const SET_SIGNUP_SUCCESS = 'SET_SIGNUP_SUCCESS';
export const SET_SIGNUP_FAILURE = 'SET_SIGNUP_FAILURE';

